# This is a configuration file for the config package written
# by RStudio. To use, make sure the package `config` is installed,
# via console:
#
# R > install.packages("config")
#
# Then, you can load within a notebook chunk with `library(config)`.
#
# To use default config settings, simply write `config::get()`.
#
# You can learn more at:
#   https://cran.r-project.org/web/packages/config/vignettes/introduction.html.
default:
  path:
    data:         
        raw_group: "/Volumes/shlab/Projects/VNI/data/mriBehaviorRaw/groupLevelFiles"
        raw_singleSub: "/Volumes/shlab/Projects/VNI/data/mriBehaviorRaw/singleSubjectFiles"
        clean: "/Volumes/shlab/Projects/VNI/data/mriBehaviorClean"
        timing_files: "/Volumes/shlab/Projects/VNI/data/mriTimingFiles"
        quality_analysis_output: "/Volumes/shlab/Projects/VNI/data/mriBehaviorQAoutput"
  csvs:
    RDM_group_clean_csv: "group_mriBehavior_clean.csv"
    RDM_group_raw_csv: "mriBehaviorRawCombined.csv"
  Rdata:
    RDM_qualityCheck: "behQualCheck.Rdata"
    RDM_exclude: "subID_exclude.Rdata"
    RDM_clean_trialnumPgam: "subID_missedT_totalT_pGam_N48.Rdata"
    RDM_group_clean_Rdata: "group_mriBehavior_clean.Rdata"




